apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-blue
  namespace: aceest
  labels:
    app: aceest-fitness
    color: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aceest-fitness
      color: blue
  template:
    metadata:
      labels:
        app: aceest-fitness
        color: blue
    spec:
      containers:
      - name: aceest
        image: your-dockerhub-username/aceest-fitness:blue
        ports:
        - containerPort: 5000
