apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-green
  namespace: aceest
  labels:
    app: aceest-fitness
    color: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aceest-fitness
      color: green
  template:
    metadata:
      labels:
        app: aceest-fitness
        color: green
    spec:
      containers:
      - name: aceest
        image: your-dockerhub-username/aceest-fitness:green
        ports:
        - containerPort: 5000
